08:38:33 [App     ] Build date: Dec 14 2021, 18:26:02
08:38:33 [App     ] CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 cores)
08:38:33 [App     ] RAM: 15.55GB Physical Memory 8.80GB Virtual Memory
08:38:33 [App     ] OS: Linux 5.10.84-1-lts (x86_64)
08:38:33 [App     ] SSE & AVX compatible CPU & OS detected
08:38:33 [App     ] Command line: /home/edin/Downloads/testset_ga_result/scene.mvs
08:38:33 [App     ] CUDA error: cuInit(0) (CUDA_ERROR_NO_DEVICE (code 100) - no CUDA-capable device is detected)
08:38:33 [App     ] Camera model loaded: platform 0; camera  0; f 1.835x1.835; poses 14
08:38:33 [App     ] Scene loaded from interface format (14ms):
	14 images (14 calibrated) with a total of 79.41 MPixels (5.67 MPixels/image)
	21724 points, 0 vertices, 0 faces
08:38:33 [App     ] error: failed loading image header
08:38:33 [App     ] error: failed loading image header
08:38:33 [App     ] error: failed loading image header
08:38:33 [App     ] error: failed loading image header
08:38:33 [App     ] error: failed loading image header
08:38:33 [App     ] error: failed loading image header
08:38:33 [App     ] error: failed loading image header
08:38:33 [App     ] error: failed loading image header
08:38:33 [App     ] error: failed reloading image '/home/edin/Python/externalSoftware/openMVS_Linux/undistorted_images/IMG_3476.jpg'
08:38:33 [App     ] error: failed reloading image '/home/edin/Python/externalSoftware/openMVS_Linux/undistorted_images/IMG_3476.jpg'
08:38:33 [App     ] error: failed reloading image '/home/edin/Python/externalSoftware/openMVS_Linux/undistorted_images/IMG_3480.jpg'
08:38:33 [App     ] error: failed reloading image '/home/edin/Python/externalSoftware/openMVS_Linux/undistorted_images/IMG_3482.jpg'
08:38:33 [App     ] error: failed reloading image '/home/edin/Python/externalSoftware/openMVS_Linux/undistorted_images/IMG_3482.jpg'
08:38:33 [App     ] error: failed reloading image '/home/edin/Python/externalSoftware/openMVS_Linux/undistorted_images/IMG_3482.jpg'
08:38:33 [App     ] error: failed reloading image '/home/edin/Python/externalSoftware/openMVS_Linux/undistorted_images/IMG_3482.jpg'
08:38:33 [App     ] error: failed reloading image '/home/edin/Python/externalSoftware/openMVS_Linux/undistorted_images/IMG_3482.jpg'
08:38:33 [App     ] error: preparing images for dense reconstruction failed (errors loading images)
